/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemoryRepoIdRouteImport } from './routes/memory.$repoId'
import { Route as ChatRepoIdRouteImport } from './routes/chat.$repoId'

const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRepoIdRoute = MemoryRepoIdRouteImport.update({
  id: '/memory/$repoId',
  path: '/memory/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRepoIdRoute = ChatRepoIdRouteImport.update({
  id: '/chat/$repoId',
  path: '/chat/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/chat/$repoId': typeof ChatRepoIdRoute
  '/memory/$repoId': typeof MemoryRepoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/chat/$repoId': typeof ChatRepoIdRoute
  '/memory/$repoId': typeof MemoryRepoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/chat/$repoId': typeof ChatRepoIdRoute
  '/memory/$repoId': typeof MemoryRepoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analyze' | '/chat/$repoId' | '/memory/$repoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyze' | '/chat/$repoId' | '/memory/$repoId'
  id: '__root__' | '/' | '/analyze' | '/chat/$repoId' | '/memory/$repoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  ChatRepoIdRoute: typeof ChatRepoIdRoute
  MemoryRepoIdRoute: typeof MemoryRepoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/$repoId': {
      id: '/memory/$repoId'
      path: '/memory/$repoId'
      fullPath: '/memory/$repoId'
      preLoaderRoute: typeof MemoryRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$repoId': {
      id: '/chat/$repoId'
      path: '/chat/$repoId'
      fullPath: '/chat/$repoId'
      preLoaderRoute: typeof ChatRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  ChatRepoIdRoute: ChatRepoIdRoute,
  MemoryRepoIdRoute: MemoryRepoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
